# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4


trigger:
- master

name: $(Build.DefinitionName)_1.0.$(Rev:r)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'



steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Free Trial (a61dc725-1165-443c-829c-35df82c38f9e)'
    KeyVaultName: 'RozeComputingVault'
    SecretsFilter: '*'
    RunAsPreJob: true
    
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'

#Uncomment this to run unit tests -NEED TO set up external mssql connections for test database before doing this
#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

#Uncomment this to Start pushing to Artifacts feed -NEED TO make sure nupkg values contain correct versioning.
#- task: NuGetCommand@2
#  inputs:
#    command: 'push'
#    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
#    nuGetFeedType: 'internal'
#    publishVstsFeed: '5f9dcefa-b54d-4051-92d0-b46d87bb0162/6fa778e5-f11a-4284-a3a6-2b011fb88e10'


